version: "3.9"
name: mombank
services:
  postgres:
    image: postgres:16.2-alpine3.19
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=mom_bank
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "root", "-d", "mom_bank"]
      interval: 3s
      timeout: 3s
      retries: 5
      
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:9999"
    env_file:
      - ./app.env
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/mom_bank?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    # entrypoint: ["/app/entrypoint.sh"]  # 명시하는 경우 dockerfile 내부의 cmd 가 무시됨
    # command: ["/app/main"]  # 명시하는 경우 dockerfile cmd override, 그렇지 않은 경우 dockerfile 의 cmd 사용



