root = "."
tmp_dir = "tmp"

[build]
    bin = "./tmp/app"
    cmd = "go build -o ./tmp/app ./cmd/app/*.go"
    delay= 20
    exclude_dir = ["assets", "tmp", "vendor"]
    exclude_file = []
    exclude_regex = [".*_templ.go"]
    exclude_unchanged = false
    follow_symlink = false
    full_bin = ""
    include_dir = []
    include_ext = ["go", "tpl", "tmpl", "templ", "html"]
    kill_delay = "0s"
    log = "build-errors.log"
    send_interrupt = false
    stop_on_error = true
#    pre_cmd = ["templ generate"]

[color]
    app = ""
    build = "yellow"
    main = "magenta"
    runner = "green"
    watcher = "cyan"

[log]
    time = false

[mics]
    clean_on_exit = false

[screen]
    clear_on_rebuild = false
    keep_scroll = true

[proxy]
    enabled = true
    proxy_port = 8090
    app_port = 8080