apiVersion: apps/v1
kind: Deployment
metadata:
  name: smoker-server
  labels:
    app: smoker-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smoker-server
  template:
    metadata:
      labels:
        app: smoker-server
    spec:
      containers:
        - name: smoker-server
          image: smoker-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: tcp
              containerPort: 8080
              protocol: TCP
            - name: udp
              containerPort: 8081
              protocol: UDP
            - name: http
              containerPort: 8082
              protocol: TCP
          env:
            - name: TCP_PORT
              value: "8080"
            - name: UDP_PORT
              value: "8081"
            - name: HTTP_PORT
              value: "8082"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: smoker-server
  labels:
    app: smoker-server
spec:
  type: ClusterIP
  selector:
    app: smoker-server
  ports:
    - name: tcp
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: udp
      port: 8081
      targetPort: 8081
      protocol: UDP
    - name: http
      port: 8082
      targetPort: 8082
      protocol: TCP
